default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: blog_application_development

test:
  <<: *default
  database: blog_application_test

production:
  <<: *default
  database: blog_application_production
  username: <%= ENV.fetch("DATABASE_USERNAME", "root") %>
  password: <%= ENV["BLOG_APPLICATION_DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
